In [14]:
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()
doc = nlp("This is some text that I am processing with Spacy")
line=''
for token in doc:
    line= nlp(token.text)
    vectorTokenized = line.vector
    meanofVector = vectorTokenized.mean()
    print(token.text,meanofVector)

This 0.010848771
is -0.0076462827
some -0.032185014
text -0.0089756325
that 0.021138815
I 0.0011596432
am 0.0026861026
processing -0.0079232305
with -0.003716752
Spacy 0.021927724

In [24]:
import zipfile
import pandas as pd
 
data = pd.read_csv('archive.zip',compression='zip')
data = data.head(5)
y = data['sentiment'].replace({'positive': 1, 'negative': 0})
print(y, data)

0    1
1    1
2    1
3    0
4    1
Name: sentiment, dtype: int64                                               review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [25]:
inputMeans=[]
for index, row in data.iterrows():
    inputMeans.append([])
    rowText = nlp(row['review'])
    for token in rowText:
        lineToken= nlp(token.text)
        vectorTokenized = lineToken.vector
        meanOfVector = vectorTokenized.mean()
        inputMeans[index].append(meanOfVector)

In [26]:
x= pd.DataFrame(inputMeans)
x

,0,1,2,3,4,5,6,7,8,9,...,349,350,351,352,353,354,355,356,357,358
0,0.021577,0.007362,-0.012018,-0.014315,-0.008056,0.003146,-0.007447,0.021139,-0.009257,0.001493,...,-0.012423,0.044766,-0.006958,-0.015123,-0.006147,-0.003717,-0.010683,-0.012644,-0.006645,0.006869
1,0.016262,-0.048202,-0.021175,-0.017137,0.006869,0.057338,0.001860,0.035583,0.015235,-0.028182,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.001160,0.001980,0.006571,-0.015239,-0.015828,-0.048202,-0.001316,0.011616,-0.009869,0.001146,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.012464,-0.013060,0.005666,-0.015828,-0.024570,0.043623,-0.015828,-0.021175,0.013520,0.013173,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.010133,0.007558,0.005666,0.015053,0.001768,-0.015123,-0.012018,0.011427,0.007362,-0.003630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN